<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="yinons-MBP-2" name="Tests.LoginTests2" tests="9" failures="1" timestamp="27 Jun 2019 08:31:17 GMT" time="38.873" errors="0">
  <testcase name="LoginClickable" time="3.209" classname="Tests.LoginTests2"/>
  <testcase name="DoLogin" time="3.915" classname="Tests.LoginTests2"/>
  <testcase name="FillPasswordWithOutToFillEmail" time="3.565" classname="Tests.LoginTests2"/>
  <testcase name="FillEmailWithOutToFillPassword" time="4.770" classname="Tests.LoginTests2"/>
  <testcase name="ClickLoginwWithOutToFillAnyFields" time="2.656" classname="Tests.LoginTests2"/>
  <testcase name="FillCorrectEmailWithWrongPassword" time="6.073" classname="Tests.LoginTests2"/>
  <testcase name="FillCorrectPasswordWithWrongEmail" time="4.170" classname="Tests.LoginTests2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Tests.LoginTests2.FillCorrectPasswordWithWrongEmail(LoginTests2.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FillCorrectPasswordWithWrongEmail -->
  <testcase name="FillWrongCarectersEmail" time="5.066" classname="Tests.LoginTests2"/>
  <testcase name="FillWrongCarectersPassword" time="5.449" classname="Tests.LoginTests2"/>
</testsuite> <!-- Tests.LoginTests2 -->
